[{
    "collection": {
        "items": {
            "Overlay1": {
                "id": "Overlay1",
                "artifactRenderStyle": "BlurbControl",
                "artifactTypeId": "BlurbOverlayVisual",
                "margin-left": 15,
                "margin-top": 100,
                "title": "asad",
                "subDescription": "<div><p>asdasda</p></div>",
                "fontColor": "#FFFCFCFC",
                "launchArtifact": "OverlayExpanded",
                "showDescription": true,
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.LaunchArtifact",
                "horizontalAlignment": "Left",
                "verticalAlignment": "Bottom"
            },
            "OverlayExpanded": {
                "id": "OverlayExpanded",
                "artifactRenderStyle": "SidebarText",
                "title": "About the disaster",
                "artifactTypeId": "TextOverlayVisual",
                "description": "<div><p>What happened?</p><p>Very heavy, sudden rainfall (‘cloudbursts’) over Nimo-Basgo during the night of 4th-5th August 2010 and over Leh between 01:30 – 02:00 IST on 6th August 2010 set off flash floods and mudslides which caused loss of life and homes, severe damage to property and to critical infrastructure.</p><p>Why?</p><p>A cloudburst is an extreme weather event in which very heavy rainfall occurs over a highly localised area in a very short timespan.</p><p>Ladakh is not known to be frequently affected by this type of phenomena.</p><p>Cloudbursts in India occur during monsoon season over mountain regions in the Himalayas, north-eastern states and the Western Ghats. The associated convective clouds can extend up to 15km above the ground. Analysis by the India Meteorological Department of satellite images for 4th – 6th August 2010 indicate that an intense convective system developed in the easterly current which is associated with the monsoon conditions over the region. The convective cloud band extended from the southeast to the northwest over Nepal and India during the afternoon of 5th August. It gradually intensified and moved west-northwest towards the Ladakh region. An intense convective cloud cluster developed to the east of Leh by 21:30 IST on 5th August.</p><p>Geologically, the region around Leh is made up of granites and loose sediments.The mountain slopes around Leh are covered in loose, unconsolidated deposits. Large fans of loose sediment, which are the product of several million years of erosion, can be observed in many locations along the banks of the Indus River. These sediments become dislodged and move rapidly when the surface layer becomes heavily saturated.The very heavy rainfall over Nimoo-Basgo and Leh on 4th – 6th August saturated the loose sediment, setting off mudslides and sand flows which travelled down-slope towards the Indus River. The destruction at locations throughout Leh district was due to the rapid movement of huge volumes of water charged with mud, boulders, trees, building debris and other objects swept up in the flow. At Choglamsar (among the worst affected areas), the debris flow travelled approximately 10km from the epicenter of the cloudburst (near Saboo), spreading up to 2km. In Leh, the debris flow travelled about 3km, from an elevation of 3800m to 3410m, confined to the catchments of Shaksaling stream. The flow destroyed settlements, the Bus Stand and the BSNL mobile communications hub, and damaged the Sonam Norboo Memorial Hospital and the radio station.</p><p>Source: India Meteorological Department; Geological Survey of India</p><br /><p>Ladakh Flood Information Hub</p><br /><br /></div>"
            },
            "Overlay2": {
                "id": "Overlay2",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/damagedhouses.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 9,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 9,
                "playInPlace": false,
                "smallMedia": "/Media/damagedhouses.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Left",
                "verticalAlignment": "Bottom",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Flood Damage in Domkhar Barma"
            },
            "Overlay3": {
                "id": "Overlay3",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/LandscapeGeography.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 9,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 9,
                "playInPlace": false,
                "smallMedia": "/Media/LandscapeGeography.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Top",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Valley Geography"
            },
            "Overlay4": {
                "id": "Overlay4",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/YakWoman.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 23,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 23,
                "playInPlace": false,
                "smallMedia": "/Media/YakWoman.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Top",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Yak Woman"
            },
            "Overlay5": {
                "id": "Overlay5",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/Livestock_Sheep_long_sm.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 30,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 30,
                "playInPlace": false,
                "smallMedia": "/Media/Livestock_Sheep_long_sm.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Top",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": ""
            },
            "Overlay6": {
                "id": "Overlay6",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/OldGompa.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 20,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 20,
                "playInPlace": false,
                "smallMedia": "/Media/OldGompa.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Bottom",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Old Gompa in Domkhar Gongma"
            },
            "Overlay7": {
                "id": "Overlay7",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/OldNew.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 20,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 20,
                "playInPlace": false,
                "smallMedia": "/Media/OldNew.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Bottom",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Old Gompa in Domkhar Gongma"
            },
            "Overlay8": {
                "id": "Overlay8",
                "src": "http://az17600.vo.msecnd.net/rincontent/Published/19d7fc7c-fe29-4d3a-b833-a373f40a77d3/LadakhRIN_01_Media/DomkharName.mp4",
                "defaultExpandedModeBehavior": "MicrosoftResearch.Rin.Behaviors.Popup",
                "artifactTypeId": "MediaOverlayVisual",
                "smallMediaStartOffset": 0,
                "smallMediaDuration": 20,
                "largeMediaStartOffset": 0,
                "largeMediaDuration": 20,
                "playInPlace": false,
                "smallMedia": "/Media/DomkharName.jpg",
                "srcType": "Video",
                "horizontalAlignment": "Right",
                "verticalAlignment": "Top",
                "margin-left": 15,
                "margin-top": 0,
                "margin-right": 15,
                "margin-bottom": 0,
                "title": "Old and New Gongma"
            }
        },
        "layout": {
            "groups": []
        }
    }
}]